# Generated by Django 4.2.29 on 2026-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, help_text='Unique batch identifier', max_length=64, unique=True)),
                ('source', models.CharField(help_text='Source of the batch', max_length=100)),
                ('total_count', models.IntegerField(default=0, help_text='Total logs in batch')),
                ('success_count', models.IntegerField(default=0, help_text='Successfully processed logs')),
                ('failed_count', models.IntegerField(default=0, help_text='Failed log count')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('errors', models.JSONField(blank=True, help_text='Error details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Batch',
                'verbose_name_plural': 'Log Batches',
                'db_table': 'logs_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Service description', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether service is active')),
                ('log_count', models.IntegerField(default=0, help_text='Total logs from this service')),
                ('last_log_at', models.DateTimeField(blank=True, help_text='Last log timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'logs_service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Log timestamp')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, help_text='Log level', max_length=20)),
                ('message', models.TextField(help_text='Log message content')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Source IP address')),
                ('service', models.CharField(db_index=True, help_text='Service name that generated the log', max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='User ID if available', max_length=100, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP request method', max_length=10)),
                ('request_path', models.CharField(blank=True, help_text='Request path', max_length=500)),
                ('user_agent', models.CharField(blank=True, help_text='Client user agent', max_length=500)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('analyzed', models.BooleanField(db_index=True, default=False, help_text='Whether log has been analyzed by AI')),
                ('ai_threat_detected', models.BooleanField(default=False, help_text='AI detected threat')),
                ('ai_threat_type', models.CharField(blank=True, help_text='Type of threat detected by AI', max_length=100)),
                ('ai_severity', models.CharField(blank=True, help_text='Threat severity level', max_length=20)),
                ('ai_analysis', models.JSONField(blank=True, help_text='Full AI analysis result', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='logs_log_timesta_08a54b_idx'), models.Index(fields=['-timestamp', 'service'], name='logs_log_timesta_214d7c_idx'), models.Index(fields=['ip_address', '-timestamp'], name='logs_log_ip_addr_3da7d5_idx')],
            },
        ),
    ]
