# Generated by Django 5.2.12 on 2026-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='logs_log_ts_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='logs_log_ts_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='logs_log_ip_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='logs_log_threat_ts_idx',
        ),
        migrations.AddField(
            model_name='log',
            name='channel',
            field=models.CharField(blank=True, help_text='Windows Event Channel (e.g., Microsoft-Windows-Sysmon/Operational)', max_length=200),
        ),
        migrations.AddField(
            model_name='log',
            name='computer',
            field=models.CharField(blank=True, help_text='Source computer name', max_length=200),
        ),
        migrations.AddField(
            model_name='log',
            name='destination_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Destination IP address', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='destination_port',
            field=models.IntegerField(blank=True, help_text='Destination port', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='dns_query',
            field=models.CharField(blank=True, help_text='DNS query string', max_length=500),
        ),
        migrations.AddField(
            model_name='log',
            name='dns_result',
            field=models.TextField(blank=True, help_text='DNS query result'),
        ),
        migrations.AddField(
            model_name='log',
            name='event_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Windows Event ID (e.g., 1 for Sysmon Process Create)', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='event_type',
            field=models.CharField(blank=True, choices=[('SYSMON_PROCESS', 'Sysmon - Process Create'), ('SYSMON_FILE', 'Sysmon - File Create'), ('SYSMON_NETWORK', 'Sysmon - Network Connection'), ('SYSMON_REGISTRY', 'Sysmon - Registry Change'), ('SYSMON_WMI', 'Sysmon - WMI Event'), ('SYSMON_IMAGE', 'Sysmon - Image Load'), ('SYSMON_CREATE_REMOTE_THREAD', 'Sysmon - Create Remote Thread'), ('SYSMON_RAW_ACCESS_READ', 'Sysmon - Raw Access Read'), ('SYSMON_PROCESS_ACCESS', 'Sysmon - Process Access'), ('SYSMON_FILE_DELETE', 'Sysmon - File Delete'), ('SYSMON_CERTIFICATE', 'Sysmon - Certificate'), ('SYSMON_PIPE_EVENT', 'Sysmon - Pipe Event'), ('SYSMON_WMI_FILTER', 'Sysmon - WMI Filter'), ('SYSMON_DNS_QUERY', 'Sysmon - DNS Query'), ('SYSMON_FILE_DELETE_LOG', 'Sysmon - File Delete Log'), ('SYSMON_PROCESS_TAMPERING', 'Sysmon - Process Tampering'), ('SYSMON_ERROR', 'Windows Error'), ('SYSMON_SECURITY', 'Windows Security'), ('SYSMON_APPLICATION', 'Windows Application'), ('OTHER', 'Other')], help_text='Event type/category', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='file_name',
            field=models.CharField(blank=True, help_text='File name that was created/deleted', max_length=1000),
        ),
        migrations.AddField(
            model_name='log',
            name='file_path',
            field=models.TextField(blank=True, help_text='Full file path'),
        ),
        migrations.AddField(
            model_name='log',
            name='parent_command_line',
            field=models.TextField(blank=True, help_text='Parent process command line'),
        ),
        migrations.AddField(
            model_name='log',
            name='parent_process_id',
            field=models.IntegerField(blank=True, help_text='Parent Process ID (PPID)', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='parent_process_name',
            field=models.CharField(blank=True, help_text='Parent process name', max_length=500),
        ),
        migrations.AddField(
            model_name='log',
            name='parent_process_path',
            field=models.CharField(blank=True, help_text='Full path to parent process', max_length=1000),
        ),
        migrations.AddField(
            model_name='log',
            name='process_command_line',
            field=models.TextField(blank=True, help_text='Full command line of the process'),
        ),
        migrations.AddField(
            model_name='log',
            name='process_hash',
            field=models.CharField(blank=True, help_text='Process file hash (MD5/SHA256)', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='process_id',
            field=models.IntegerField(blank=True, help_text='Process ID (PID)', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='process_name',
            field=models.CharField(blank=True, help_text='Process name that was created/accessed', max_length=500),
        ),
        migrations.AddField(
            model_name='log',
            name='process_path',
            field=models.CharField(blank=True, help_text='Full path to the process executable', max_length=1000),
        ),
        migrations.AddField(
            model_name='log',
            name='protocol',
            field=models.CharField(blank=True, help_text='Network protocol (TCP/UDP)', max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='provider_name',
            field=models.CharField(blank=True, help_text='Event Provider Name', max_length=200),
        ),
        migrations.AddField(
            model_name='log',
            name='raw_event_data',
            field=models.JSONField(blank=True, help_text='Raw Windows Event Log data', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='registry_key',
            field=models.TextField(blank=True, help_text='Registry key path'),
        ),
        migrations.AddField(
            model_name='log',
            name='registry_value',
            field=models.TextField(blank=True, help_text='Registry value data'),
        ),
        migrations.AddField(
            model_name='log',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Source IP address', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='source_port',
            field=models.IntegerField(blank=True, help_text='Source port', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user_name',
            field=models.CharField(blank=True, help_text='User who generated the event', max_length=200),
        ),
    ]
