# Generated by Django 4.2.29 on 2026-03-05 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Alert title', max_length=255)),
                ('description', models.TextField(help_text='Detailed alert description')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, help_text='Alert severity level', max_length=20)),
                ('threat_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_ip', 'Suspicious IP'), ('repeated_errors', 'Repeated Errors'), ('unusual_access', 'Unusual Access Pattern'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('ddos', 'DDoS Attack'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('malware', 'Malware Detected'), ('other', 'Other')], help_text='Type of threat detected', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Related IP address', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='new', help_text='Alert status', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('source_log', models.ForeignKey(blank=True, help_text='Source log that triggered the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='logs.log')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('threat_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_ip', 'Suspicious IP'), ('repeated_errors', 'Repeated Errors'), ('unusual_access', 'Unusual Access Pattern'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('ddos', 'DDoS Attack'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('malware', 'Malware Detected'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('min_occurrences', models.IntegerField(default=1)),
                ('time_window_minutes', models.IntegerField(default=5)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('auto_block_ip', models.BooleanField(default=False)),
                ('auto_create_ticket', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'db_table': 'alerts_rule',
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
            ],
            options={
                'verbose_name': 'Alert Notification',
                'verbose_name_plural': 'Alert Notifications',
                'db_table': 'alerts_notification',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to block', unique=True)),
                ('reason', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_activity', 'Suspicious Activity'), ('manual', 'Manually Blocked'), ('ddos', 'DDoS Attack'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('other', 'Other')], help_text='Reason for blocking', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the block')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the block expires (null = permanent)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the block is currently active')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'db_table': 'alerts_blockedip',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='alerts_bloc_ip_addr_07ec1b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at', 'status'], name='alerts_aler_created_4286c9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='alerts_aler_severit_12d0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['threat_type'], name='alerts_aler_threat__3409ac_idx'),
        ),
    ]
