# Generated by Django 5.2.12 on 2026-03-07 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_performance_indexes'),
        ('logs', '0003_remove_log_logs_log_ts_level_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_created_sev_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_sev_status_idx',
        ),
        migrations.AddField(
            model_name='alert',
            name='cwe_id',
            field=models.CharField(blank=True, help_text='CWE (Common Weakness Enumeration) ID', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Security recommendation for this vulnerability'),
        ),
        migrations.AddField(
            model_name='alert',
            name='vulnerability_type',
            field=models.CharField(blank=True, help_text='Specific vulnerability type', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='threat_type',
            field=models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_ip', 'Suspicious IP'), ('repeated_errors', 'Repeated Errors'), ('unusual_access', 'Unusual Access Pattern'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('ddos', 'DDoS Attack'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('malware', 'Malware Detected'), ('vulnerability', 'Security Vulnerability'), ('command_injection', 'Command Injection'), ('path_traversal', 'Path Traversal'), ('weak_crypto', 'Weak Cryptography'), ('sensitive_data_exposure', 'Sensitive Data Exposure'), ('security_misconfig', 'Security Misconfiguration'), ('open_redirect', 'Open Redirect'), ('other', 'Other')], help_text='Type of threat detected', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threat_type',
            field=models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_ip', 'Suspicious IP'), ('repeated_errors', 'Repeated Errors'), ('unusual_access', 'Unusual Access Pattern'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('ddos', 'DDoS Attack'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('malware', 'Malware Detected'), ('vulnerability', 'Security Vulnerability'), ('command_injection', 'Command Injection'), ('path_traversal', 'Path Traversal'), ('weak_crypto', 'Weak Cryptography'), ('sensitive_data_exposure', 'Sensitive Data Exposure'), ('security_misconfig', 'Security Misconfiguration'), ('open_redirect', 'Open Redirect'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='reason',
            field=models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_activity', 'Suspicious Activity'), ('manual', 'Manually Blocked'), ('ddos', 'DDoS Attack'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('vulnerability', 'Vulnerability Exploit'), ('other', 'Other')], help_text='Reason for blocking', max_length=50),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['cwe_id'], name='alerts_aler_cwe_id_7e4204_idx'),
        ),
    ]
